#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=$(find $prefix -iname "*.gpg" | grep -v ".git" | sed 's/.*\.password-store\/\(.*\)\.gpg/\1/')
password=$(printf '%s\n' "${password_files[@]}" | dmenu -i "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" 2>/dev/null
    username=$(pass show "$password" | grep -o -P "user(name)?: \K.*")
    notify-send "username: $username"
    echo "$username" | xclip  # send the username to middle button paste
else
    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
    xdotool type --clearmodifiers --file -
fi
