#!/usr/bin/env bash

shopt -s nullglob globstar

typeit=0
if [[ $1 == "--type" ]]; then
    typeit=1
    shift
fi

prefix=${PASSWORD_STORE_DIR-~/.password-store}
password=$(cd $prefix && find * -type f -iname "*.gpg" -exec sh -c 'printf "%s\n" "${@%.gpg}"' _ {} + | bemenu -l 10 --scrollbar autohide -p "Pass:" -i "$@")

[[ -n $password ]] || exit

if [[ $typeit -eq 0 ]]; then
    pass show -c "$password" 2>/dev/null
    username=$(pass show "$password" | grep -o -P "user(name)?: \K.*")
    notify-send "username: $username"
    echo "$username" | wl-copy --primary  # send the username to middle button paste
else
    pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } | ydotool type --file -
fi
